const urls = import.meta.glob('../assets/audio/*/*.ogg', {
  query: '?url',
  import: 'default',
  eager: true,
});

export const audioAssets = {
  investigation: { url: urls['../assets/audio/bgm/investigation.ogg'], loop: true, volume: 0.45 },
  reconstruction: { url: urls['../assets/audio/bgm/reconstruction.ogg'], loop: true, volume: 0.45 },
  deduction: { url: urls['../assets/audio/bgm/deduction.ogg'], loop: true, volume: 0.45 },
  'final-attendance': {
    url: urls['../assets/audio/bgm/final-attendance.ogg'],
    loop: false,
    volume: 0.45,
  },
  'island-wind': {
    url: urls['../assets/audio/ambience/island-wind.ogg'],
    loop: true,
    volume: 0.42,
  },
  'empty-school': {
    url: urls['../assets/audio/ambience/empty-school.ogg'],
    loop: true,
    volume: 0.42,
  },
  'ui-cursor': { url: urls['../assets/audio/sfx/ui-cursor.ogg'], loop: false, volume: 0.7 },
  'ui-confirm': { url: urls['../assets/audio/sfx/ui-confirm.ogg'], loop: false, volume: 0.7 },
  'ui-back': { url: urls['../assets/audio/sfx/ui-back.ogg'], loop: false, volume: 0.7 },
  'notebook-open': { url: urls['../assets/audio/sfx/notebook-open.ogg'], loop: false, volume: 0.7 },
  'evidence-record': {
    url: urls['../assets/audio/sfx/evidence-record.ogg'],
    loop: false,
    volume: 0.7,
  },
  'testimony-record': {
    url: urls['../assets/audio/sfx/testimony-record.ogg'],
    loop: false,
    volume: 0.7,
  },
  'replay-enter': { url: urls['../assets/audio/sfx/replay-enter.ogg'], loop: false, volume: 0.7 },
  'replay-exit': { url: urls['../assets/audio/sfx/replay-exit.ogg'], loop: false, volume: 0.7 },
  'report-confirm': {
    url: urls['../assets/audio/sfx/report-confirm.ogg'],
    loop: false,
    volume: 0.7,
  },
  'all-confirmed': { url: urls['../assets/audio/sfx/all-confirmed.ogg'], loop: false, volume: 0.7 },
  footsteps: { url: urls['../assets/audio/sfx/footsteps.ogg'], loop: false, volume: 0.7 },
  'door-latch': { url: urls['../assets/audio/sfx/door-latch.ogg'], loop: false, volume: 0.7 },
  'bed-drag': { url: urls['../assets/audio/sfx/bed-drag.ogg'], loop: false, volume: 0.7 },
  'water-drips': { url: urls['../assets/audio/sfx/water-drips.ogg'], loop: false, volume: 0.7 },
  'water-splash': { url: urls['../assets/audio/sfx/water-splash.ogg'], loop: false, volume: 0.7 },
  'broadcast-chime': {
    url: urls['../assets/audio/sfx/broadcast-chime.ogg'],
    loop: false,
    volume: 0.7,
  },
  'distant-gunshot': {
    url: urls['../assets/audio/sfx/distant-gunshot.ogg'],
    loop: false,
    volume: 0.7,
  },
  'mechanism-stop': {
    url: urls['../assets/audio/sfx/mechanism-stop.ogg'],
    loop: false,
    volume: 0.7,
  },
  'broadcast-switch': {
    url: urls['../assets/audio/sfx/broadcast-switch.ogg'],
    loop: false,
    volume: 0.7,
  },
  'chair-fall-tableware': {
    url: urls['../assets/audio/sfx/chair-fall-tableware.ogg'],
    loop: false,
    volume: 0.7,
  },
  'heavy-book-return': {
    url: urls['../assets/audio/sfx/heavy-book-return.ogg'],
    loop: false,
    volume: 0.7,
  },
  'book-drop': { url: urls['../assets/audio/sfx/book-drop.ogg'], loop: false, volume: 0.7 },
  'cloth-cane': { url: urls['../assets/audio/sfx/cloth-cane.ogg'], loop: false, volume: 0.7 },
  'catwalk-metal': { url: urls['../assets/audio/sfx/catwalk-metal.ogg'], loop: false, volume: 0.7 },
  'delivery-envelope': {
    url: urls['../assets/audio/sfx/delivery-envelope.ogg'],
    loop: false,
    volume: 0.7,
  },
  'mirror-camera': { url: urls['../assets/audio/sfx/mirror-camera.ogg'], loop: false, volume: 0.7 },
  'cart-stop-scissors': {
    url: urls['../assets/audio/sfx/cart-stop-scissors.ogg'],
    loop: false,
    volume: 0.7,
  },
  'projector-loop': {
    url: urls['../assets/audio/sfx/projector-loop.ogg'],
    loop: true,
    volume: 0.7,
  },
  'projector-stop': {
    url: urls['../assets/audio/sfx/projector-stop.ogg'],
    loop: false,
    volume: 0.7,
  },
  'clothes-rack-fall': {
    url: urls['../assets/audio/sfx/clothes-rack-fall.ogg'],
    loop: false,
    volume: 0.7,
  },
  'crate-collapse': {
    url: urls['../assets/audio/sfx/crate-collapse.ogg'],
    loop: false,
    volume: 0.7,
  },
  'player-piano': { url: urls['../assets/audio/sfx/player-piano.ogg'], loop: false, volume: 0.7 },
  'sign-flip': { url: urls['../assets/audio/sfx/sign-flip.ogg'], loop: false, volume: 0.7 },
  'keys-jingle': { url: urls['../assets/audio/sfx/keys-jingle.ogg'], loop: false, volume: 0.7 },
  'drain-finish': { url: urls['../assets/audio/sfx/drain-finish.ogg'], loop: false, volume: 0.7 },
  'medical-tools': { url: urls['../assets/audio/sfx/medical-tools.ogg'], loop: false, volume: 0.7 },
  'warning-buzzer-stop': {
    url: urls['../assets/audio/sfx/warning-buzzer-stop.ogg'],
    loop: false,
    volume: 0.7,
  },
  'transmitter-start': {
    url: urls['../assets/audio/sfx/transmitter-start.ogg'],
    loop: false,
    volume: 0.7,
  },
  'door-knock': { url: urls['../assets/audio/sfx/door-knock.ogg'], loop: false, volume: 0.7 },
  'terminal-scheduled': {
    url: urls['../assets/audio/sfx/terminal-scheduled.ogg'],
    loop: false,
    volume: 0.7,
  },
  'report-print': { url: urls['../assets/audio/sfx/report-print.ogg'], loop: false, volume: 0.7 },
};
